name: CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --no-restore --configuration Release

    - name: Upload Release Artifact
      id: upload-release
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts
        path: "./Tiptup300.ScriptRunner.ConsoleApplication/bin/Release/net8.0/"

  test: 
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal --configuration Release


  deploy:
    needs: test
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: release-artifacts

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Check outputs
      run: echo ${{ env.sha_short }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.sha_short }}
        release_name: Release ${{ env.sha_short }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false

    - name: Zip Artifacts
      run: |
        cd ./Tiptup300.ScriptRunner.ConsoleApplication/bin/Release/net8.0/
        zip -r artifacts.zip .

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Tiptup300.ScriptRunner.ConsoleApplication/bin/Release/net8.0/artifacts.zip
        asset_name: artifacts.zip
        asset_content_type: application/zip