name: CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --no-restore --configuration Release

    - name: Upload Release Artifact
      id: upload-release
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts
        path: "./Tiptup300.ScriptRunner.ConsoleApplication/bin/Release/net8.0/"

  test: 
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal --configuration Release


  deploy:
     needs: test
     runs-on: windows-latest
     permissions:
       contents: write
     steps:
     - name: Checkout Code
       uses: actions/checkout@v3
  
     - name: Download Build Artifacts
       uses: actions/download-artifact@v4
       with:
         name: release-artifacts
         path: release-artifacts
  
     - name: Set outputs
       id: vars
       shell: bash
       run: |
         echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
  
     - name: Create Release
       uses: softprops/action-gh-release@v1
       with:
         tag_name: ${{ steps.vars.outputs.sha_short }}
         name: Release ${{ steps.vars.outputs.sha_short }}
         body: |
           Changes in this Release
           - First Change
           - Second Change
         draft: false
         prerelease: false
         files: |
           release-artifacts/*
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}